apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/s4e_Task2.git
    targetRevision: HEAD
    path: helm/codegen
  destination:
    server: https://kubernetes.default.svc
    namespace: codegen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
